// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UtEq_ozPg_rRWo714QTqapSV6LimWCo',
    appId: '1:1089903895364:web:ac5d3de507db48759ced11',
    messagingSenderId: '1089903895364',
    projectId: 'profile-app-001',
    authDomain: 'profile-app-001.firebaseapp.com',
    storageBucket: 'profile-app-001.appspot.com',
    measurementId: 'G-QDTM76LNZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOInTbG-oqW04m-CxsGfZQxlDsfil9NPA',
    appId: '1:1089903895364:android:ceb04fee53e609999ced11',
    messagingSenderId: '1089903895364',
    projectId: 'profile-app-001',
    storageBucket: 'profile-app-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPixxj6kgpxAQzMzcP4voa7n99ZscB-QU',
    appId: '1:1089903895364:ios:42102860c1c4b0bb9ced11',
    messagingSenderId: '1089903895364',
    projectId: 'profile-app-001',
    storageBucket: 'profile-app-001.appspot.com',
    iosBundleId: 'com.example.profileApp',
  );
}
